# Generated by Django 3.2.3 on 2023-07-31 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_contract', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('annual_nfd_quota', models.IntegerField(default=0)),
                ('nfds_used_to_date', models.IntegerField(default=0)),
                ('off_reduced_rep_tot', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_status', models.CharField(choices=[('PL', 'Playing'), ('RE', 'Reserve'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('off_reduced_rep', models.BooleanField(default=False)),
                ('trialist', models.BooleanField(default=False)),
                ('guest_principal', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.player')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('players', models.ManyToManyField(through='string_rota.PlayerProject', to='string_rota.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instrumentation', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'repertoire',
            },
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('REH', 'Rehersal'), ('CON', 'Concert'), ('REC', 'Recording')], default='REH', max_length=3)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='string_rota.project')),
                ('repertoire', models.ManyToManyField(related_name='sessions', to='string_rota.Repertoire')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('players', models.ManyToManyField(related_name='sections', to='string_rota.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SeatingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.player')),
                ('seating_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='string_rota.seatingplan')),
            ],
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='players',
            field=models.ManyToManyField(related_name='s_plans_players', through='string_rota.SeatingPosition', to='string_rota.Player'),
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_plans_project', to='string_rota.project'),
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.section'),
        ),
        migrations.AddField(
            model_name='project',
            name='repertoire_name',
            field=models.ManyToManyField(related_name='repertoire', to='string_rota.Repertoire'),
        ),
        migrations.AddField(
            model_name='project',
            name='seating_plan',
            field=models.ManyToManyField(related_name='project_s_plan', to='string_rota.SeatingPlan'),
        ),
        migrations.AddField(
            model_name='project',
            name='sessions',
            field=models.ManyToManyField(related_name='project_sessions', to='string_rota.Session'),
        ),
        migrations.AddField(
            model_name='playerproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.project'),
        ),
        migrations.AddField(
            model_name='player',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.section'),
        ),
        migrations.AddField(
            model_name='player',
            name='users_django',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
