# Generated by Django 3.2.3 on 2023-07-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='players',
        ),
    ]
