# Generated by Django 3.2.3 on 2022-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(max_length=200, unique=True)),
                ('intrumentation', models.CharField(max_length=14)),
            ],
        ),
    ]
