# Generated by Django 3.2.3 on 2023-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0002_remove_section_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='players',
            field=models.ManyToManyField(related_name='sections', to='string_rota.Player'),
        ),
    ]
