# Generated by Django 3.2.3 on 2023-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0003_section_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatingposition',
            name='position_number',
            field=models.PositiveIntegerField(),
        ),
    ]
