# Generated by Django 3.2.3 on 2022-12-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0003_rename_intrumentation_repertoire_instrumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRepertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='string_rota.project')),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.repertoire')),
            ],
        ),
    ]
