# Generated by Django 3.2.3 on 2023-08-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0004_alter_seatingposition_position_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplan',
            name='custom_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='default_strength',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
