# Generated by Django 3.2.5 on 2023-10-03 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('string_rota', '0005_auto_20230801_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='users_django',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
