# Generated by Django 3.2.3 on 2022-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0005_auto_20221212_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectrepertoire',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectrepertoire',
            name='repertoire',
        ),
        migrations.AlterModelOptions(
            name='repertoire',
            options={'verbose_name_plural': 'repertoire'},
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectRepertoire',
        ),
    ]
