# Generated by Django 3.2.3 on 2022-12-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('string_rota', '0007_alter_section_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=50, unique=True)),
                ('player_last_name', models.CharField(max_length=50, unique=True)),
                ('is_contract', models.BooleanField(default=True)),
                ('player_notes', models.TextField()),
                ('annual_nfd_quota', models.IntegerField(default=0)),
                ('nfds_used_to_date', models.IntegerField(default=0)),
                ('off_reduced_rep_tot', models.IntegerField(default=0)),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.section')),
                ('users_django_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
