# Generated by Django 3.2.3 on 2022-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0008_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertoire',
            name='rep_name',
            field=models.CharField(max_length=200),
        ),
    ]
