# Generated by Django 3.2.3 on 2022-12-19 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('string_rota', '0009_alter_repertoire_rep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='users_django_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
