# Generated by Django 3.2.3 on 2022-12-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0010_alter_player_users_django_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_last_name',
            field=models.CharField(max_length=50),
        ),
    ]
