# Generated by Django 3.2.3 on 2022-12-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0011_auto_20221219_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='section_name',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='users_django_id',
            new_name='users_django',
        ),
        migrations.RenameField(
            model_name='repertoire',
            old_name='rep_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='section_name',
            new_name='name',
        ),
    ]
