# Generated by Django 3.2.3 on 2022-12-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0012_auto_20221219_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_start_time', models.DateTimeField()),
                ('session_end_time', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('REH', 'Rehersal'), ('CON', 'Concert'), ('REC', 'Recording')], default='REH', max_length=3)),
                ('repertoire_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.repertoire')),
            ],
        ),
    ]
