# Generated by Django 3.2.3 on 2022-12-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0013_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_start_time',
            new_name='start_time',
        ),
    ]
