# Generated by Django 3.2.3 on 2022-12-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0014_auto_20221219_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='repertoire_id',
            new_name='repertoire',
        ),
    ]
