# Generated by Django 3.2.3 on 2022-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0015_auto_20221219_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repertoire_name',
            field=models.ManyToManyField(to='string_rota.Repertoire'),
        ),
    ]
