# Generated by Django 3.2.3 on 2022-12-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0017_auto_20221220_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='repertoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.repertoire'),
        ),
    ]
