# Generated by Django 3.2.3 on 2022-12-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0018_alter_session_repertoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='repertoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='string_rota.repertoire'),
        ),
    ]
