# Generated by Django 3.2.3 on 2022-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0019_alter_session_repertoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='repertoire',
        ),
        migrations.AddField(
            model_name='session',
            name='repertoire',
            field=models.ManyToManyField(null=True, to='string_rota.Repertoire'),
        ),
    ]
