# Generated by Django 3.2.3 on 2022-12-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0021_alter_session_repertoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='string_rota.session'),
        ),
    ]
