# Generated by Django 3.2.3 on 2022-12-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0022_project_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='string_rota.project'),
        ),
    ]
