# Generated by Django 3.2.3 on 2022-12-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0023_auto_20221220_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sessions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_sessions', to='string_rota.session'),
        ),
    ]
