# Generated by Django 3.2.3 on 2022-12-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0024_project_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sessions',
        ),
    ]
