# Generated by Django 3.2.3 on 2022-12-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0025_remove_project_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seating_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seating_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.player')),
                ('seating_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='string_rota.seating_plan')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.section')),
            ],
        ),
        migrations.AddField(
            model_name='seating_plan',
            name='player',
            field=models.ManyToManyField(through='string_rota.Seating_Position', to='string_rota.Player'),
        ),
        migrations.AddField(
            model_name='seating_plan',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='string_rota.project'),
        ),
        migrations.AddField(
            model_name='seating_plan',
            name='seating_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postition', to='string_rota.seating_position'),
        ),
        migrations.AddField(
            model_name='seating_plan',
            name='section_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.section'),
        ),
        migrations.AddField(
            model_name='project',
            name='seating_plan',
            field=models.ManyToManyField(through='string_rota.Seating_Plan', to='string_rota.Seating_Position'),
        ),
    ]
