# Generated by Django 3.2.3 on 2022-12-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0026_auto_20221220_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_status', models.CharField(choices=[('PL', 'Playing'), ('RE', 'Reserve'), ('NA', 'Not Available')], default='PL', max_length=2)),
                ('off_reduced_rep', models.BooleanField(default=False)),
                ('trialist', models.BooleanField(default=False)),
                ('guest_principal', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.player')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='string_rota.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='player',
            field=models.ManyToManyField(through='string_rota.Player_Project', to='string_rota.Player'),
        ),
    ]
