# Generated by Django 3.2.3 on 2022-12-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0027_auto_20221220_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seating_plan',
            old_name='project_id',
            new_name='project',
        ),
    ]
