# Generated by Django 3.2.3 on 2022-12-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0028_rename_project_id_seating_plan_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seating_position',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='seating_position',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='project',
            name='seating_plan',
        ),
        migrations.RemoveField(
            model_name='seating_plan',
            name='player',
        ),
        migrations.RemoveField(
            model_name='seating_plan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='seating_plan',
            name='seating_position',
        ),
        migrations.RemoveField(
            model_name='seating_position',
            name='seating_plan',
        ),
    ]
