# Generated by Django 3.2.3 on 2022-12-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0029_auto_20221220_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating_plan',
            name='player',
            field=models.ManyToManyField(through='string_rota.Seating_Position', to='string_rota.Player'),
        ),
        migrations.AddField(
            model_name='seating_plan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_plan', to='string_rota.project'),
        ),
        migrations.AddField(
            model_name='seating_plan',
            name='seating_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postition', to='string_rota.seating_position'),
        ),
        migrations.AddField(
            model_name='seating_position',
            name='seating_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='string_rota.seating_plan'),
        ),
    ]
