# Generated by Django 3.2.3 on 2022-12-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0032_project_seating_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sessions',
            field=models.ManyToManyField(related_name='session', to='string_rota.Session'),
        ),
    ]
