# Generated by Django 3.2.3 on 2022-12-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0038_auto_20221221_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_project',
            name='performance_status',
            field=models.CharField(choices=[('PL', 'Playing'), ('RE', 'Reserve'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
    ]
