# Generated by Django 3.2.3 on 2022-12-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0039_alter_player_project_performance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='player',
            new_name='players',
        ),
    ]
