# Generated by Django 3.2.3 on 2023-07-31 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0043_auto_20221226_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_status', models.CharField(choices=[('PL', 'Playing'), ('RE', 'Reserve'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('off_reduced_rep', models.BooleanField(default=False)),
                ('trialist', models.BooleanField(default=False)),
                ('guest_principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SeatingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='seating_plan',
            name='players',
        ),
        migrations.RemoveField(
            model_name='seating_plan',
            name='project',
        ),
        migrations.RemoveField(
            model_name='seating_plan',
            name='section',
        ),
        migrations.RemoveField(
            model_name='seating_position',
            name='player',
        ),
        migrations.RemoveField(
            model_name='seating_position',
            name='seating_plan',
        ),
        migrations.AlterField(
            model_name='player',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.section'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repertoire_name',
            field=models.ManyToManyField(related_name='repertoire_name', to='string_rota.Repertoire'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sessions',
            field=models.ManyToManyField(related_name='sessions', to='string_rota.Session'),
        ),
        migrations.AlterField(
            model_name='section',
            name='players',
            field=models.ManyToManyField(related_name='players', to='string_rota.Player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='string_rota.project'),
        ),
        migrations.AlterField(
            model_name='session',
            name='repertoire',
            field=models.ManyToManyField(related_name='repertoire', to='string_rota.Repertoire'),
        ),
        migrations.DeleteModel(
            name='Player_Project',
        ),
        migrations.DeleteModel(
            name='Seating_Plan',
        ),
        migrations.DeleteModel(
            name='Seating_Position',
        ),
        migrations.AddField(
            model_name='seatingposition',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.player'),
        ),
        migrations.AddField(
            model_name='seatingposition',
            name='seating_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='string_rota.seatingplan'),
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='players',
            field=models.ManyToManyField(related_name='seating_players', through='string_rota.SeatingPosition', to='string_rota.Player'),
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_plan', to='string_rota.project'),
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.section'),
        ),
        migrations.AddField(
            model_name='playerproject',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.player'),
        ),
        migrations.AddField(
            model_name='playerproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='string_rota.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='players',
            field=models.ManyToManyField(through='string_rota.PlayerProject', to='string_rota.Player'),
        ),
        migrations.AlterField(
            model_name='project',
            name='seating_plan',
            field=models.ManyToManyField(related_name='seating_plan', to='string_rota.SeatingPlan'),
        ),
    ]
