# Generated by Django 3.2.3 on 2023-07-31 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('string_rota', '0045_auto_20230731_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repertoire_name',
            field=models.ManyToManyField(related_name='repertoire', to='string_rota.Repertoire'),
        ),
        migrations.AlterField(
            model_name='project',
            name='seating_plan',
            field=models.ManyToManyField(related_name='project_s_plan', to='string_rota.SeatingPlan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sessions',
            field=models.ManyToManyField(related_name='project_sessions', to='string_rota.Session'),
        ),
        migrations.AlterField(
            model_name='seatingplan',
            name='players',
            field=models.ManyToManyField(related_name='s_plans_players', through='string_rota.SeatingPosition', to='string_rota.Player'),
        ),
        migrations.AlterField(
            model_name='seatingplan',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_plans_project', to='string_rota.project'),
        ),
        migrations.AlterField(
            model_name='section',
            name='players',
            field=models.ManyToManyField(related_name='sections', to='string_rota.Player'),
        ),
        migrations.AlterField(
            model_name='session',
            name='repertoire',
            field=models.ManyToManyField(related_name='sessions', to='string_rota.Repertoire'),
        ),
    ]
